# Generated by Django 4.2.7 on 2023-11-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trineo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('anio', models.DateField()),
            ],
        ),
    ]
