# Generated by Django 4.2.7 on 2023-11-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paleta',
            name='fromato',
            field=models.TextField(max_length=30),
        ),
    ]
