# Generated by Django 4.2.7 on 2023-11-12 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_paleta_fromato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paleta',
            old_name='fromato',
            new_name='descripcion',
        ),
    ]
